### ISSUE TITLE
Broken by Sphinx 1.6.1

### ISSUE THREAD

**Issue by sigmavirus24** [bitprophet/releases#66]
If you:

- clone github.com/pypa/twine,
- update tox.ini to allow 1.6.1, and
- run `tox -e docs` you'll reproduce it. The logs from sphinx are here:

```
# Sphinx version: 1.6.1
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   making output directory...
#   loading pickled environment...
#   not yet created
#   loading intersphinx inventory from http://docs.python.org/objects.inv...
#   intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 2 source files that are out of date
#   updating environment:
#   2 added, 0 changed, 0 removed
#   reading sources... [ 50%] changelog
# Loaded extensions:
#   releases (unknown version) from /home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/releases/__init__.pyc
#   sphinx.ext.coverage (1.6.1) from /home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   alabaster (0.7.10) from /home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.autodoc (1.6.1) from /home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.doctest (1.6.1) from /home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/ext/doctest.pyc
#   sphinx.ext.viewcode (1.6.1) from /home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.intersphinx (1.6.1) from /home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
Traceback (most recent call last):
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 603, in _read_serial
    self.read_doc(docname, app)
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 718, in read_doc
    pub.publish()
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/docutils/transforms/universal.py", line 294, in apply
    txtnode.parent.replace(txtnode, nodes.Text(newtext))
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/docutils/nodes.py", line 928, in replace
    index = self.index(old)
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/docutils/nodes.py", line 689, in index
    return self.children.index(item)
  File "/home/sigmavirus24/sandbox/pypa/twine/.tox/docs/lib/python2.7/site-packages/releases/models.py", line 62, in __eq__
    if getattr(self, attr) != getattr(other, attr):
AttributeError: 'Text' object has no attribute 'type'
```

I'll take a look into fixing this later, but I don't have the time right this second. :)

**Comment by tony** [comment]
@sigmavirus24 Same, also broke on my projects when pyup PR'd the update.

**Comment by bitprophet** [comment]
Mildly worried the "default to None" fix may cause other brokenness (if we assumed the attr existed before & were using it for reasons...) but given it passes the test suite...probably fine? Thanks for the report & the PR.

**Comment by bitprophet** [comment]
> bitprophet closed this in #67 3 minutes ago

What is this (new?) witchcraft, GitHub?! Only thing I can see that might have caused that (as you can tell, I am used to having to trigger closure via changelog commits...) is that @sigmavirus24's PR says `Closes #66` in its body text...

**Comment by sigmavirus24** [comment]
I'm sneaky. 😄

**Comment by bitprophet** [comment]
So am I right about the text hint working in PR description fields as in commit messages...or do you have Github superpowers? 😮

**Comment by sigmavirus24** [comment]
So in a commit message or PR description it'll work and has since before I became a maintainer of Requests (years ago). It's not new, but it's kind of sneaky.
